### ISSUE TITLE
blink.pde not running

### ISSUE THREAD

**Issue by csquared** [kyab/mruby-arduino#13]
Hey @kyab - apologies for all the issues but I really want to get this working!

I've made the changes to my Arduino IDE files and can compile and upload the sample to my Arduino Due!  However, when I use the Serial Monitor the only output I see is "Hello Arduino".  The program doesn't even get to the "mruby initialized" line. Any suggestions for how to troubleshoot?

http://cl.ly/image/0r2n223a2e0r

The multiple "Hello Arduino" lines are from me resetting.

Thanks!

**Comment by kyab** [comment]
@csquared Thank you for trying.

I doubt heap(RAM) shortage. Arduino Due only has 96kb RAM. I'm usually working on chipKIT Max32(128kb RAM), or stm32f4discovery(196kb RAM), but on all of these boards, most difficult part is control heap usage(malloc()), because mruby requires some amount of RAM.
I personally still don't have Arduino Due, but some people succeeded to run mruby on Arduino Due.  But this is one of smallest boards which can run mruby.

Could you try below?
- Try with following update version of blink.pde. this will print more verbose outputs to Serial Monitor.
  https://gist.github.com/kyab/fca28611be8560c202f3
- Disable some mrbgems in your build_config.rb like this. More mrbgem you add, more RAM required.

``` ruby
...
MRuby::CrossBuild.new("Arduino Due") do |conf|
...
  #gems from core
  #conf.gem :core => "mruby-print"
  #conf.gem :core => "mruby-math"
  #conf.gem :core => "mruby-enum-ext"

  #light-weight regular expression
  #conf.gem :github => "masamitsu-murase/mruby-hs-regexp", :branch => "master"

  #Arduino API
  conf.gem :github =>"kyab/mruby-arduino", :branch => "master"  do |g|
    g.cxx.include_paths << ["#{ARDUINO_PATH}/libraries/Servo/src", "#{ARDUINO_PATH}/libraries/Servo/arch/sam"]
  end

end
...
...
```

You should rebuild mruby, then build blink.pde and upload.

**Comment by csquared** [comment]
@kyab that worked!  Thank you very much :)

**Comment by csquared** [comment]
It was recompiling without the gems that made the difference. Will spend some time changing settings to confirm.

**Comment by kyab** [comment]
Nice to hear it worked.
